//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobmatchCRMSync.LAKAServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LAKAServices.LAKAServicesSoap")]
    public interface LAKAServicesSoap {
        
        // CODEGEN: Generating message contract since element name Environment from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataSource", ReplyAction="*")]
        JobmatchCRMSync.LAKAServices.GetDataSourceResponse GetDataSource(JobmatchCRMSync.LAKAServices.GetDataSourceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataSource", ReplyAction="*")]
        System.Threading.Tasks.Task<JobmatchCRMSync.LAKAServices.GetDataSourceResponse> GetDataSourceAsync(JobmatchCRMSync.LAKAServices.GetDataSourceRequest request);
        
        // CODEGEN: Generating message contract since element name Environment from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CRMOrgService", ReplyAction="*")]
        JobmatchCRMSync.LAKAServices.CRMOrgServiceResponse CRMOrgService(JobmatchCRMSync.LAKAServices.CRMOrgServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CRMOrgService", ReplyAction="*")]
        System.Threading.Tasks.Task<JobmatchCRMSync.LAKAServices.CRMOrgServiceResponse> CRMOrgServiceAsync(JobmatchCRMSync.LAKAServices.CRMOrgServiceRequest request);
        
        // CODEGEN: Generating message contract since element name CRMOrgUsernameResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CRMOrgUsername", ReplyAction="*")]
        JobmatchCRMSync.LAKAServices.CRMOrgUsernameResponse CRMOrgUsername(JobmatchCRMSync.LAKAServices.CRMOrgUsernameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CRMOrgUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<JobmatchCRMSync.LAKAServices.CRMOrgUsernameResponse> CRMOrgUsernameAsync(JobmatchCRMSync.LAKAServices.CRMOrgUsernameRequest request);
        
        // CODEGEN: Generating message contract since element name CRMOrgPasswordResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CRMOrgPassword", ReplyAction="*")]
        JobmatchCRMSync.LAKAServices.CRMOrgPasswordResponse CRMOrgPassword(JobmatchCRMSync.LAKAServices.CRMOrgPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CRMOrgPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<JobmatchCRMSync.LAKAServices.CRMOrgPasswordResponse> CRMOrgPasswordAsync(JobmatchCRMSync.LAKAServices.CRMOrgPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name jobnavn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogStart", ReplyAction="*")]
        JobmatchCRMSync.LAKAServices.LogStartResponse LogStart(JobmatchCRMSync.LAKAServices.LogStartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogStart", ReplyAction="*")]
        System.Threading.Tasks.Task<JobmatchCRMSync.LAKAServices.LogStartResponse> LogStartAsync(JobmatchCRMSync.LAKAServices.LogStartRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataSourceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataSource", Namespace="http://tempuri.org/", Order=0)]
        public JobmatchCRMSync.LAKAServices.GetDataSourceRequestBody Body;
        
        public GetDataSourceRequest() {
        }
        
        public GetDataSourceRequest(JobmatchCRMSync.LAKAServices.GetDataSourceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataSourceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Environment;
        
        public GetDataSourceRequestBody() {
        }
        
        public GetDataSourceRequestBody(string Environment) {
            this.Environment = Environment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataSourceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataSourceResponse", Namespace="http://tempuri.org/", Order=0)]
        public JobmatchCRMSync.LAKAServices.GetDataSourceResponseBody Body;
        
        public GetDataSourceResponse() {
        }
        
        public GetDataSourceResponse(JobmatchCRMSync.LAKAServices.GetDataSourceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataSourceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataSourceResult;
        
        public GetDataSourceResponseBody() {
        }
        
        public GetDataSourceResponseBody(string GetDataSourceResult) {
            this.GetDataSourceResult = GetDataSourceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CRMOrgServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CRMOrgService", Namespace="http://tempuri.org/", Order=0)]
        public JobmatchCRMSync.LAKAServices.CRMOrgServiceRequestBody Body;
        
        public CRMOrgServiceRequest() {
        }
        
        public CRMOrgServiceRequest(JobmatchCRMSync.LAKAServices.CRMOrgServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CRMOrgServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Environment;
        
        public CRMOrgServiceRequestBody() {
        }
        
        public CRMOrgServiceRequestBody(string Environment) {
            this.Environment = Environment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CRMOrgServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CRMOrgServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public JobmatchCRMSync.LAKAServices.CRMOrgServiceResponseBody Body;
        
        public CRMOrgServiceResponse() {
        }
        
        public CRMOrgServiceResponse(JobmatchCRMSync.LAKAServices.CRMOrgServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CRMOrgServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CRMOrgServiceResult;
        
        public CRMOrgServiceResponseBody() {
        }
        
        public CRMOrgServiceResponseBody(string CRMOrgServiceResult) {
            this.CRMOrgServiceResult = CRMOrgServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CRMOrgUsernameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CRMOrgUsername", Namespace="http://tempuri.org/", Order=0)]
        public JobmatchCRMSync.LAKAServices.CRMOrgUsernameRequestBody Body;
        
        public CRMOrgUsernameRequest() {
        }
        
        public CRMOrgUsernameRequest(JobmatchCRMSync.LAKAServices.CRMOrgUsernameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CRMOrgUsernameRequestBody {
        
        public CRMOrgUsernameRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CRMOrgUsernameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CRMOrgUsernameResponse", Namespace="http://tempuri.org/", Order=0)]
        public JobmatchCRMSync.LAKAServices.CRMOrgUsernameResponseBody Body;
        
        public CRMOrgUsernameResponse() {
        }
        
        public CRMOrgUsernameResponse(JobmatchCRMSync.LAKAServices.CRMOrgUsernameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CRMOrgUsernameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CRMOrgUsernameResult;
        
        public CRMOrgUsernameResponseBody() {
        }
        
        public CRMOrgUsernameResponseBody(string CRMOrgUsernameResult) {
            this.CRMOrgUsernameResult = CRMOrgUsernameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CRMOrgPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CRMOrgPassword", Namespace="http://tempuri.org/", Order=0)]
        public JobmatchCRMSync.LAKAServices.CRMOrgPasswordRequestBody Body;
        
        public CRMOrgPasswordRequest() {
        }
        
        public CRMOrgPasswordRequest(JobmatchCRMSync.LAKAServices.CRMOrgPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CRMOrgPasswordRequestBody {
        
        public CRMOrgPasswordRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CRMOrgPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CRMOrgPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public JobmatchCRMSync.LAKAServices.CRMOrgPasswordResponseBody Body;
        
        public CRMOrgPasswordResponse() {
        }
        
        public CRMOrgPasswordResponse(JobmatchCRMSync.LAKAServices.CRMOrgPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CRMOrgPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CRMOrgPasswordResult;
        
        public CRMOrgPasswordResponseBody() {
        }
        
        public CRMOrgPasswordResponseBody(string CRMOrgPasswordResult) {
            this.CRMOrgPasswordResult = CRMOrgPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogStartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogStart", Namespace="http://tempuri.org/", Order=0)]
        public JobmatchCRMSync.LAKAServices.LogStartRequestBody Body;
        
        public LogStartRequest() {
        }
        
        public LogStartRequest(JobmatchCRMSync.LAKAServices.LogStartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogStartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jobnavn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string con;
        
        public LogStartRequestBody() {
        }
        
        public LogStartRequestBody(string jobnavn, string con) {
            this.jobnavn = jobnavn;
            this.con = con;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogStartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogStartResponse", Namespace="http://tempuri.org/", Order=0)]
        public JobmatchCRMSync.LAKAServices.LogStartResponseBody Body;
        
        public LogStartResponse() {
        }
        
        public LogStartResponse(JobmatchCRMSync.LAKAServices.LogStartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LogStartResponseBody {
        
        public LogStartResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LAKAServicesSoapChannel : JobmatchCRMSync.LAKAServices.LAKAServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LAKAServicesSoapClient : System.ServiceModel.ClientBase<JobmatchCRMSync.LAKAServices.LAKAServicesSoap>, JobmatchCRMSync.LAKAServices.LAKAServicesSoap {
        
        public LAKAServicesSoapClient() {
        }
        
        public LAKAServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LAKAServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LAKAServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LAKAServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JobmatchCRMSync.LAKAServices.GetDataSourceResponse JobmatchCRMSync.LAKAServices.LAKAServicesSoap.GetDataSource(JobmatchCRMSync.LAKAServices.GetDataSourceRequest request) {
            return base.Channel.GetDataSource(request);
        }
        
        public string GetDataSource(string Environment) {
            JobmatchCRMSync.LAKAServices.GetDataSourceRequest inValue = new JobmatchCRMSync.LAKAServices.GetDataSourceRequest();
            inValue.Body = new JobmatchCRMSync.LAKAServices.GetDataSourceRequestBody();
            inValue.Body.Environment = Environment;
            JobmatchCRMSync.LAKAServices.GetDataSourceResponse retVal = ((JobmatchCRMSync.LAKAServices.LAKAServicesSoap)(this)).GetDataSource(inValue);
            return retVal.Body.GetDataSourceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JobmatchCRMSync.LAKAServices.GetDataSourceResponse> JobmatchCRMSync.LAKAServices.LAKAServicesSoap.GetDataSourceAsync(JobmatchCRMSync.LAKAServices.GetDataSourceRequest request) {
            return base.Channel.GetDataSourceAsync(request);
        }
        
        public System.Threading.Tasks.Task<JobmatchCRMSync.LAKAServices.GetDataSourceResponse> GetDataSourceAsync(string Environment) {
            JobmatchCRMSync.LAKAServices.GetDataSourceRequest inValue = new JobmatchCRMSync.LAKAServices.GetDataSourceRequest();
            inValue.Body = new JobmatchCRMSync.LAKAServices.GetDataSourceRequestBody();
            inValue.Body.Environment = Environment;
            return ((JobmatchCRMSync.LAKAServices.LAKAServicesSoap)(this)).GetDataSourceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JobmatchCRMSync.LAKAServices.CRMOrgServiceResponse JobmatchCRMSync.LAKAServices.LAKAServicesSoap.CRMOrgService(JobmatchCRMSync.LAKAServices.CRMOrgServiceRequest request) {
            return base.Channel.CRMOrgService(request);
        }
        
        public string CRMOrgService(string Environment) {
            JobmatchCRMSync.LAKAServices.CRMOrgServiceRequest inValue = new JobmatchCRMSync.LAKAServices.CRMOrgServiceRequest();
            inValue.Body = new JobmatchCRMSync.LAKAServices.CRMOrgServiceRequestBody();
            inValue.Body.Environment = Environment;
            JobmatchCRMSync.LAKAServices.CRMOrgServiceResponse retVal = ((JobmatchCRMSync.LAKAServices.LAKAServicesSoap)(this)).CRMOrgService(inValue);
            return retVal.Body.CRMOrgServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JobmatchCRMSync.LAKAServices.CRMOrgServiceResponse> JobmatchCRMSync.LAKAServices.LAKAServicesSoap.CRMOrgServiceAsync(JobmatchCRMSync.LAKAServices.CRMOrgServiceRequest request) {
            return base.Channel.CRMOrgServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<JobmatchCRMSync.LAKAServices.CRMOrgServiceResponse> CRMOrgServiceAsync(string Environment) {
            JobmatchCRMSync.LAKAServices.CRMOrgServiceRequest inValue = new JobmatchCRMSync.LAKAServices.CRMOrgServiceRequest();
            inValue.Body = new JobmatchCRMSync.LAKAServices.CRMOrgServiceRequestBody();
            inValue.Body.Environment = Environment;
            return ((JobmatchCRMSync.LAKAServices.LAKAServicesSoap)(this)).CRMOrgServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JobmatchCRMSync.LAKAServices.CRMOrgUsernameResponse JobmatchCRMSync.LAKAServices.LAKAServicesSoap.CRMOrgUsername(JobmatchCRMSync.LAKAServices.CRMOrgUsernameRequest request) {
            return base.Channel.CRMOrgUsername(request);
        }
        
        public string CRMOrgUsername() {
            JobmatchCRMSync.LAKAServices.CRMOrgUsernameRequest inValue = new JobmatchCRMSync.LAKAServices.CRMOrgUsernameRequest();
            inValue.Body = new JobmatchCRMSync.LAKAServices.CRMOrgUsernameRequestBody();
            JobmatchCRMSync.LAKAServices.CRMOrgUsernameResponse retVal = ((JobmatchCRMSync.LAKAServices.LAKAServicesSoap)(this)).CRMOrgUsername(inValue);
            return retVal.Body.CRMOrgUsernameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JobmatchCRMSync.LAKAServices.CRMOrgUsernameResponse> JobmatchCRMSync.LAKAServices.LAKAServicesSoap.CRMOrgUsernameAsync(JobmatchCRMSync.LAKAServices.CRMOrgUsernameRequest request) {
            return base.Channel.CRMOrgUsernameAsync(request);
        }
        
        public System.Threading.Tasks.Task<JobmatchCRMSync.LAKAServices.CRMOrgUsernameResponse> CRMOrgUsernameAsync() {
            JobmatchCRMSync.LAKAServices.CRMOrgUsernameRequest inValue = new JobmatchCRMSync.LAKAServices.CRMOrgUsernameRequest();
            inValue.Body = new JobmatchCRMSync.LAKAServices.CRMOrgUsernameRequestBody();
            return ((JobmatchCRMSync.LAKAServices.LAKAServicesSoap)(this)).CRMOrgUsernameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JobmatchCRMSync.LAKAServices.CRMOrgPasswordResponse JobmatchCRMSync.LAKAServices.LAKAServicesSoap.CRMOrgPassword(JobmatchCRMSync.LAKAServices.CRMOrgPasswordRequest request) {
            return base.Channel.CRMOrgPassword(request);
        }
        
        public string CRMOrgPassword() {
            JobmatchCRMSync.LAKAServices.CRMOrgPasswordRequest inValue = new JobmatchCRMSync.LAKAServices.CRMOrgPasswordRequest();
            inValue.Body = new JobmatchCRMSync.LAKAServices.CRMOrgPasswordRequestBody();
            JobmatchCRMSync.LAKAServices.CRMOrgPasswordResponse retVal = ((JobmatchCRMSync.LAKAServices.LAKAServicesSoap)(this)).CRMOrgPassword(inValue);
            return retVal.Body.CRMOrgPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JobmatchCRMSync.LAKAServices.CRMOrgPasswordResponse> JobmatchCRMSync.LAKAServices.LAKAServicesSoap.CRMOrgPasswordAsync(JobmatchCRMSync.LAKAServices.CRMOrgPasswordRequest request) {
            return base.Channel.CRMOrgPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<JobmatchCRMSync.LAKAServices.CRMOrgPasswordResponse> CRMOrgPasswordAsync() {
            JobmatchCRMSync.LAKAServices.CRMOrgPasswordRequest inValue = new JobmatchCRMSync.LAKAServices.CRMOrgPasswordRequest();
            inValue.Body = new JobmatchCRMSync.LAKAServices.CRMOrgPasswordRequestBody();
            return ((JobmatchCRMSync.LAKAServices.LAKAServicesSoap)(this)).CRMOrgPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JobmatchCRMSync.LAKAServices.LogStartResponse JobmatchCRMSync.LAKAServices.LAKAServicesSoap.LogStart(JobmatchCRMSync.LAKAServices.LogStartRequest request) {
            return base.Channel.LogStart(request);
        }
        
        public void LogStart(string jobnavn, string con) {
            JobmatchCRMSync.LAKAServices.LogStartRequest inValue = new JobmatchCRMSync.LAKAServices.LogStartRequest();
            inValue.Body = new JobmatchCRMSync.LAKAServices.LogStartRequestBody();
            inValue.Body.jobnavn = jobnavn;
            inValue.Body.con = con;
            JobmatchCRMSync.LAKAServices.LogStartResponse retVal = ((JobmatchCRMSync.LAKAServices.LAKAServicesSoap)(this)).LogStart(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JobmatchCRMSync.LAKAServices.LogStartResponse> JobmatchCRMSync.LAKAServices.LAKAServicesSoap.LogStartAsync(JobmatchCRMSync.LAKAServices.LogStartRequest request) {
            return base.Channel.LogStartAsync(request);
        }
        
        public System.Threading.Tasks.Task<JobmatchCRMSync.LAKAServices.LogStartResponse> LogStartAsync(string jobnavn, string con) {
            JobmatchCRMSync.LAKAServices.LogStartRequest inValue = new JobmatchCRMSync.LAKAServices.LogStartRequest();
            inValue.Body = new JobmatchCRMSync.LAKAServices.LogStartRequestBody();
            inValue.Body.jobnavn = jobnavn;
            inValue.Body.con = con;
            return ((JobmatchCRMSync.LAKAServices.LAKAServicesSoap)(this)).LogStartAsync(inValue);
        }
    }
}
